//WInterface autogenerated this file. HaND

#include "sample.wi.h"











#pragma mark -
#pragma mark Implementations:










// !!!: Implementations: a


















#define _ClassName_ AA
#define _WIClass_ AA__
#define _className_ aA
#define _Class_ AA__
@implementation AA

-(AA*)_startObjectOfClassAA {MSGSTART("AA:-(AA*)_startObjectOfClassAA")
  {
            //@-999 NSDictionary *d __attribute__((unused)) =([self respondsToSelector:@selector(__initializeUsingDictionary)]?[self performSelector:@selector(__initializeUsingDictionary)]:nil);
            
    /*i999*/return(self);
        }}
-(AA*)a {MSGSTART("AA:-(AA*)a")
  
  /*i-999*/AA* ret=v_a;
  /*i999*/return(ret);}
-(void)dealloc {MSGSTART("AA:-(void)dealloc")
  
  /*i-151*/[self die];
/*i0*/{
    REMOVEOWNER(v_a,self);v_a=nil;
/*i999*/}}
-(void)die {MSGSTART("AA:-(void)die")
  {
    /*i900*/}}
-(void)fn {MSGSTART("AA:-(void)fn")
  {}}
-(void)setA:(AA*)v {MSGSTART("AA:-(void)setA:(AA*)v")
  
  /*i-905*/if(v_a==v)return;
  /*i-900*/{v_a=(id)v;}
/*i-850*/REMOVEOWNER(v_a,self);ADDOWNER(v,self);}
- {MSGSTART("AA:-")
  {
    hi
    }}

@end
#undef _ClassName_
#undef _WIClass_
#undef _className_
#undef _Class_


















