//Minim autogenerated this file. HaND

#include "sample.wi.decl.h"
@protocol ClassObject;
@protocol DerivedObject;
@protocol Object;
@class AA;











#pragma mark -
#pragma mark Protocols:

@protocol ClassObject 

@end









@protocol DerivedObject 

@end









@protocol Object 

@end




















#pragma mark -
#pragma mark Interfaces

@interface AA : NSObject<Object, ClassObject> {
    AA* v_a;
}

@property (strong,nonatomic,readwrite) AA* a;
-(AA*)_startObjectOfClassAA;
-(AA*)a;
-(void)dealloc;
-(void)die;
-(void)fn;
-(void)setA:(AA*)v;
-;

@end


















