// WInterface autogenerated this file. HaND



#pragma mark -
#pragma mark Interfaces:
#ifdef INCLUDE_IFACE

    #ifdef INCLUDE_IFACE_D0





        @interface AA : NSObject<Object, ClassObject> {
            AA *v_a;
        }

        @property (strong,nonatomic,readwrite) AA *a;
        - (void)_startObjectOfClassAA;
        - (AA *)a;
        - (void)dealloc;
        - (void)die;
        - (void)fn;
        - (void)setA:(AA *)v;

        @end
    #endif // INCLUDE_IFACE_D0

#else  // INCLUDE_IFACE





    #pragma mark -
    #pragma mark Implementations:





// !!!: Implementations: a





    #define _ClassName_ AA
    #define _WIClass_   AA__
    #define _className_ aA
    #define _Class_     AA__
    @implementation AA

    - (void)_startObjectOfClassAA {
        MSGSTART("AA:-(void)_startObjectOfClassAA")
    }
    - (AA *)a {
        MSGSTART("AA:-(AA*)a")

        /*i-999*/ AA * ret = v_a;
        /*i999*/ return ret;
    }
    - (void)dealloc {
        MSGSTART("AA:-(void)dealloc")

        /*i-151*/[self die];
/*i0*/ REMOVEOWNER(v_a,self); v_a = nil;
/*i999*/}
    - (void)die {
        MSGSTART("AA:-(void)die")

        /*i900*/}
    - (void)fn {
        MSGSTART("AA:-(void)fn")
    }
    - (void)setA:(AA *)v {
        MSGSTART("AA:-(void)setA:(AA*)v")

        /*i-905*/ if (v_a == v) return;

        /*i-900*/ {
            v_a = (id)v;
        }
/*i-850*/ REMOVEOWNER(v_a,self); ADDOWNER(v,self);
    }

    @end
    #undef _ClassName_
    #undef _WIClass_
    #undef _className_
    #undef _Class_
#endif  // INCLUDE_IFACE
