//WInterface autogenerated this file at 2012-12-11 18:50:31 +0000. HaND

@protocol Array;
@protocol BasicTester;
@protocol DebugRetain;
@protocol DerivedObject;
@protocol Dictionary;
@protocol LinkEndpoint;
@protocol LogObjectProtocol;
@protocol MutableArrayDelegate;
@protocol MutableDictionaryDelegate;
@protocol MutableSetDelegate;
@protocol Set;
@protocol TesterCounter;
@protocol ValueLinkEndpoint;
@protocol WeakArray;
@protocol WeakDictionary;
@protocol WeakSet;
@protocol MinimalMutableArray;
@protocol MinimalMutableDictionary;
@protocol MutableArrayIndexFollower;
@protocol MutableDictionaryKeyFollower;
@protocol MutableSet;
@protocol ObjectID;
@protocol Tester;
@protocol ArrayLinkEndpoint;
@protocol BaseObject;
@protocol DictionaryLinkEndpoint;
@protocol MutableArray;
@protocol MutableDictionary;
@protocol MutableSetMirrorTester;
@protocol SetLinkEndpoint;
@protocol TrackerMutableArray;
@protocol TrackerMutableSet;
@protocol MutableArrayMirrorTester;
@protocol MutableDictionaryMirrorTester;
@protocol TrackerMutableDictionary;
@class CollectionTestObject;
@class CollectionTestSubObject;
@class IndexToIndexMap;
@class IntCarrier;
@class ObjectRegistry;
@class Util;
@class AtomiclyMutableArray;
@class AtomiclyMutableDictionary;
@class AtomiclyMutableSet;
@class Endpoint1;
@class PointerKey;
@class WeakObject;
@class ArrayTester;
@class DictionaryTester;
@class MutableSet;
@class ObjectPointer;
@class SetTester;
@class WeakMutableSet;
@class EndpointA;
@class EndpointA_tracker;
@class EndpointD;
@class EndpointS;
@class EndpointS_tracker;
@class Model;
@class MutableArray;
@class MutableDictionary;
@class MutableSetMirrorTesterImpl;
@class TrackerMutableArray;
@class TrackerMutableSet;
@class WeakMutableArray;
@class WeakMutableDictionary;
@class WeakMutableSetMirrorTesterImpl;
@class EndpointD_tracker;
@class MutableArrayMirrorTesterImpl;
@class MutableDictionaryMirrorTesterImpl;
@class TrackerMutableDictionary;
@class WeakMutableArrayMirrorTesterImpl;
@class WeakMutableDictionaryMirrorTesterImpl;









