// WInterface autogenerated this file. HaND

// Tasks:
// Embedded 2 notes (look for "MARK:WI:" in the code)




#pragma mark -
#pragma mark Interfaces:
#ifdef INCLUDE_IFACE

    #ifdef INCLUDE_IFACE_D0





        @interface WeakSelf : NSObject<Object, ClassObject> {
            LL __owner_context;
            @private ULL __private_access_thread_mask_in_WeakSelf; @protected
            bool debugAutorelease;
            Unsigned hash;
            Unsigned index;
            bool isZombie;
            LL objectIDInClass;
            LL objectIDInTotal;
            id strongSelf;
        }

        @property (nonatomic,readwrite) LL __owner_context;
        @property (nonatomic,readonly) constchar *cdescription;
        @property (nonatomic,readonly) constchar *cobjectName;
        @property (nonatomic,readwrite) bool debugAutorelease;
        @property (nonatomic,readonly) NSString *description;
        @property (nonatomic,readonly) Unsigned hash;
        @property (nonatomic,readonly) Unsigned index;
        @property (nonatomic,readonly) bool isZombie;
        @property (nonatomic,readonly) LL objectIDInClass;
        @property (nonatomic,readonly) LL objectIDInTotal;
        @property (nonatomic,readonly) NSMutableString *objectName;
        @property (weak,nonatomic,readonly) id strongSelf;
        - (void)_startObjectOfClassWeakSelf;
        - (constchar *)cdescription;
        - (constchar *)cobjectName;
        - (instancetype)copyWithZone:(NSZone *)zone;
        - (void)dealloc;
        - (NSString *)description;
        - (void)die;
        - (instancetype)initCopyFrom:(WeakSelf *)copy;
        - (instancetype)initWithStrongSelf:(id)astrongSelf;
        - (BOOL)isEqual:(id)object;
        - (bool)isWeakSelf;
        - (NSMutableString *)objectName;
        - (id)selfWithWeakness:(bool)weak;
        - (id)strongSelf;
        - (WeakSelf *)weakSelf;
        + (WeakSelf *)weakSelfFromObject:(id)astrongSelf;

        @end
    #endif // INCLUDE_IFACE_D0

#else  // INCLUDE_IFACE





    #pragma mark -
    #pragma mark Implementations:





// !!!: Implementations: w





    #ifdef _PrivateAccessMask_
        #undef _PrivateAccessMask_
    #endif
    #define _PrivateAccessMask_ __private_access_thread_mask_in_Globals

    #define _ClassName_         WeakSelf
    #define _WIClass_           WeakSelf__
    #define _className_         weakSelf
    #define _Class_             WeakSelf__
    @implementation WeakSelf

    @synthesize __owner_context = __owner_context;
    @synthesize debugAutorelease = debugAutorelease;
    @synthesize hash = hash;
    @synthesize index = index;
    @synthesize isZombie = isZombie;
    @synthesize objectIDInClass = objectIDInClass;
    @synthesize objectIDInTotal = objectIDInTotal;
    - (void)_startObjectOfClassWeakSelf {
        MSGSTART("WeakSelf:-(void)_startObjectOfClassWeakSelf")

        /*i-996*/ debugAutorelease = YES;
        /*i-995*/ objInitFn(self,objectIDInTotal,objectIDInClass);

        /*i0*/}
    - (constchar *)cdescription {
        MSGSTART("WeakSelf:-(constchar*)cdescription")
        return [self.description cStringUsingEncoding:NSASCIIStringEncoding];
    }
    - (constchar *)cobjectName {
        MSGSTART("WeakSelf:-(constchar*)cobjectName")
        return [self.objectName cStringUsingEncoding:NSASCIIStringEncoding];
    }
    - (instancetype)copyWithZone:(NSZone *)zone {
        MSGSTART("WeakSelf:-(instancetype)copyWithZone:(NSZone *)zone")
        return [[WeakSelf allocWithZone:zone] initCopyFrom:self];
    }
    - (void)dealloc {
        MSGSTART("WeakSelf:-(void)dealloc")

        /*i-151*/[self die];
/*i998*/ deallocFn(self,objectIDInTotal,objectIDInClass);
        isZombie = YES;
    #if defined (LONGLIVEZOMBIES) || defined (LONGLIVEZOMBIES___WI_CLASS__)
            if (YES) return;
    #endif

/*i999*/}
    - (NSString *)description {
        MSGSTART("WeakSelf:-(NSString*)description")

        /*i-999*/ NSMutableString * ret = self.objectName;

        /*i999*/ return ret;
    }
    - (void)die {
        MSGSTART("WeakSelf:-(void)die")

        /*i900*/}
    - (instancetype)initCopyFrom:(WeakSelf *)copy {
        MSGSTART("WeakSelf:-(instancetype)initCopyFrom:(WeakSelf*)copy")
        if ( (self = [super init]) ) {
            index = copy->index;
            hash = copy->hash;
            strongSelf = copy->strongSelf;
        }
        return self;
    }
    - (instancetype)initWithStrongSelf:(id)astrongSelf {
        MSGSTART("WeakSelf:-(instancetype)initWithStrongSelf:(id)astrongSelf")
        static Int s_index = 0;
        if ( (self = [super init]) ) {
            index = ++s_index;
            hash = [( (strongSelf = astrongSelf) )hash];
        }
        return self;
    }
    - (BOOL)isEqual:(id)object {
        MSGSTART("WeakSelf:-(BOOL)isEqual:(id)object")
        return object && ( (object == self) || (object == strongSelf) || ([object isKindOfClass:WeakSelf.class] && ( ( (WeakSelf *)object ) )->index == index) );
    }
    - (bool)isWeakSelf {
        MSGSTART("WeakSelf:-(bool)isWeakSelf")
        return YES;
    }
    - (NSMutableString *)objectName {
        MSGSTART("WeakSelf:-(NSMutableString*)objectName")

        /*i-999*/ NSMutableString * ret = nil;

        /*i-100*/ ret = [NSMutableString stringWithFormat:@"[%qu:%p]%s#%qu",objectIDInTotal,self,__Derived_CClass__,objectIDInClass];

        /*i999*/ return ret;
    }
    - (id)selfWithWeakness:(bool)weak {
        MSGSTART("WeakSelf:-(id)selfWithWeakness:(bool)weak")
        return weak ? self : strongSelf;
    }
    - (id)strongSelf {
        MSGSTART("WeakSelf:-(id)strongSelf")

        /*i-999*/ id ret = strongSelf;
        /*i999*/ return ret;
    }
    - (WeakSelf *)weakSelf {
        MSGSTART("WeakSelf:-(WeakSelf*)weakSelf")
        return self;
    }
    + (WeakSelf *)weakSelfFromObject:(id)astrongSelf {
        MSGSTART("WeakSelf:+(WeakSelf*)weakSelfFromObject:(id)astrongSelf")
        return [[WeakSelf alloc] initWithStrongSelf:astrongSelf];
    }

    @end
    #undef _ClassName_
    #undef _WIClass_
    #undef _className_
    #undef _Class_
#endif  // INCLUDE_IFACE
