//WInterface autogenerated this file. HaND

//Tasks:
//    Embedded 5 notes (look for "notenote" in the code)


#include "sample.wi.h"











#pragma mark -
#pragma mark Implementations:










// !!!: Implementations: v



















#ifdef _PrivateAccessMask_
#undef _PrivateAccessMask_
#endif
#define _PrivateAccessMask_ __private_access_thread_mask_in_VarsAssignAtomic

#ifdef _PrivateAccessMask_
#undef _PrivateAccessMask_
#endif
#define _PrivateAccessMask_ __private_access_thread_mask_in_VarsAssignAtomic
#define _ClassName_ VarsAssignAtomic
#define _WIClass_ VarsAssignAtomic__
#define _className_ varsAssignAtomic
#define _Class_ VarsAssignAtomic__
@implementation VarsAssignAtomic

@synthesize __owner_context=__owner_context;
@synthesize debugAutorelease=debugAutorelease;
@synthesize isZombie=isZombie;
@synthesize objectIDInClass=objectIDInClass;
@synthesize objectIDInTotal=objectIDInTotal;
@synthesize rw_iv_nodef_short_zero=rw_iv_nodef_short_zero;
@synthesize rw_na_iv_def1_short_one=rw_na_iv_def1_short_one;
@synthesize rw_na_iv_nodef_short_declInVarsBase=rw_na_iv_nodef_short_declInVarsBase;
@synthesize rw_na_iv_nodef_short_nill=rw_na_iv_nodef_short_nill;
-(VarsAssignAtomic*)_startObjectOfClassVarsAssignAtomic {MSGSTART("VarsAssignAtomic:-(VarsAssignAtomic*)_startObjectOfClassVarsAssignAtomic")
  
  /*i-996*/debugAutorelease=YES;
  /*i-995*/objInitFn(self,___rc,___arc,objectIDInTotal,objectIDInClass);
      
  /*i-500*//*ivar*/v_rw_iv_Clas_settergetteri=([Clas getDefault]);  ADDOWNER(v_rw_iv_Clas_settergetteri,self);
   /*ivar*/v_pr_iv_def_Clas_publicreadonly=([Clas getDefault]);  ADDOWNER(v_pr_iv_def_Clas_publicreadonly,self);
   /*ivar*/rw_na_iv_def1_short_one=(1);
   /*ivar*/v_rw_iv_def_Clas_atomici=([Clas getDefault]);  ADDOWNER(v_rw_iv_def_Clas_atomici,self);
  
  /*i0*///@-999 NSDictionary *d __attribute__((unused)) =([self respondsToSelector:@selector(__initializeUsingDictionary)]?[self performSelector:@selector(__initializeUsingDictionary)]:nil);
          
  /*i999*/return(self);
    }
-(Clas*)___arc {MSGSTART("VarsAssignAtomic:-(Clas*)___arc")
  
  /*i-999*/Clas* ret=v____arc;
  /*i999*/return(ret);}
-(Clas*)___rc {MSGSTART("VarsAssignAtomic:-(Clas*)___rc")
  
  /*i-999*/Clas* ret=v____rc;
  /*i999*/return(ret);}
-(constchar*)cdescription {MSGSTART("VarsAssignAtomic:-(constchar*)cdescription")
  return([self.description cStringUsingEncoding:NSASCIIStringEncoding]);}
-(constchar*)cobjectName {MSGSTART("VarsAssignAtomic:-(constchar*)cobjectName")
  return([self.objectName cStringUsingEncoding:NSASCIIStringEncoding]);}
-(void)dealloc {MSGSTART("VarsAssignAtomic:-(void)dealloc")
  
  /*i-151*/[self die];
/*i0*/REMOVEOWNER(v____rc,self);v____rc=nil;
    REMOVEOWNER(v_rw_iv_Clas_settergetteri,self);v_rw_iv_Clas_settergetteri=nil;
    REMOVEOWNER(v____arc,self);v____arc=nil;
    REMOVEOWNER(v_pr_iv_def_Clas_publicreadonly,self);v_pr_iv_def_Clas_publicreadonly=nil;
    REMOVEOWNER(v_rw_jiv_Clas_justivar,self);v_rw_jiv_Clas_justivar=nil;
    REMOVEOWNER(v_rw_iv_def_Clas_atomici,self);v_rw_iv_def_Clas_atomici=nil;
    REMOVEOWNER(the_ivar_named,self);the_ivar_named=nil;
    REMOVEOWNER(v_pr_iv_Clas_ivar,self);v_pr_iv_Clas_ivar=nil;
    REMOVEOWNER(the_justivar_named,self);the_justivar_named=nil;
/*i998*/deallocFn(self,___rc,___arc,objectIDInTotal,objectIDInClass);
        isZombie=YES;
#if defined(LONGLIVEZOMBIES) || defined(LONGLIVEZOMBIES___WI_CLASS__)
        if (YES) return;
#endif
    
/*i999*/}
-(NSString*)description {MSGSTART("VarsAssignAtomic:-(NSString*)description")
  
  /*i-999*/NSMutableString *ret=self.objectName;
          
  /*i999*/return(ret);
    }
-(void)die {MSGSTART("VarsAssignAtomic:-(void)die")
  
  /*i900*/}
-(NSMutableString*)objectName {MSGSTART("VarsAssignAtomic:-(NSMutableString*)objectName")
  
  /*i-999*/NSMutableString *ret=nil;
          
  /*i-100*/ret=[NSMutableString stringWithFormat:@"[%qu:%p]%s#%qu",objectIDInTotal,self,__Derived_CClass__,objectIDInClass];
          
  /*i999*/return(ret);
    }
-(Clas*)pr_iv_Clas_getteri {MSGSTART("VarsAssignAtomic:-(Clas*)pr_iv_Clas_getteri")
  return(pr_iv_Clas_getteri);}
-(Clas*)pr_iv_Clas_ivar {MSGSTART("VarsAssignAtomic:-(Clas*)pr_iv_Clas_ivar")
  return([Clas getDefault]);}
-(Clas*)pr_iv_Clas_ivar_named {MSGSTART("VarsAssignAtomic:-(Clas*)pr_iv_Clas_ivar_named")
  return([Clas getDefault]);}
-(Clas*)pr_iv_Clas_setter {MSGSTART("VarsAssignAtomic:-(Clas*)pr_iv_Clas_setter")
  
  /*i-999*/Clas* ret;memset(&ret,0,sizeof(ret));
  /*i999*/return(ret);}
-(Clas*)pr_iv_def_Clas_publicreadonly {MSGSTART("VarsAssignAtomic:-(Clas*)pr_iv_def_Clas_publicreadonly")
  
  /*i-999*/Clas* ret=v_pr_iv_def_Clas_publicreadonly;
  /*i999*/return(ret);}
-(Clas*)r_noiv_Clas_getteri {MSGSTART("VarsAssignAtomic:-(Clas*)r_noiv_Clas_getteri")
  return([Clas getDefault]);}
-(Clas*)rw_iv_Clas_settergetter {MSGSTART("VarsAssignAtomic:-(Clas*)rw_iv_Clas_settergetter")
  return([Clas getDefault]);}
-(Clas*)rw_iv_Clas_settergetter2 {MSGSTART("VarsAssignAtomic:-(Clas*)rw_iv_Clas_settergetter2")
  return(rw_iv_Clas_settergetter2);}
-(Clas*)rw_iv_Clas_setteri {MSGSTART("VarsAssignAtomic:-(Clas*)rw_iv_Clas_setteri")
  
  /*i-999*/Clas* ret;memset(&ret,0,sizeof(ret));
  /*i999*/return(ret);}
-(Clas*)rw_iv_def_Clas_atomici {MSGSTART("VarsAssignAtomic:-(Clas*)rw_iv_def_Clas_atomici")
  
  /*i-999*/Clas* ret=v_rw_iv_def_Clas_atomici;
  /*i999*/return(ret);}
-(Clas*)rw_jiv_Clas_justivar_named {MSGSTART("VarsAssignAtomic:-(Clas*)rw_jiv_Clas_justivar_named")
  
  /*i-999*/Clas* ret=the_justivar_named;
  /*i999*/return(ret);}
-(Clas*)rw_noiv_Clas_settergetter {MSGSTART("VarsAssignAtomic:-(Clas*)rw_noiv_Clas_settergetter")
  return([Clas getDefault]);}
-(Clas*)rw_noiv_Clas_setteri {MSGSTART("VarsAssignAtomic:-(Clas*)rw_noiv_Clas_setteri")
  
  /*i-999*/Clas* ret;memset(&ret,0,sizeof(ret));
  /*i999*/return(ret);}
-(void)set___arc:(Clas*)v {MSGSTART("VarsAssignAtomic:-(void)set___arc:(Clas*)v")
  
  /*i-905*/if(v____arc==v)return;
  /*i-900*/{v____arc=(id)v;}
/*i-850*/REMOVEOWNER(v____arc,self);ADDOWNER(v,self);}
-(void)set___rc:(Clas*)v {MSGSTART("VarsAssignAtomic:-(void)set___rc:(Clas*)v")
  
  /*i-905*/if(v____rc==v)return;
  /*i-900*/{v____rc=(id)v;}
/*i-850*/REMOVEOWNER(v____rc,self);ADDOWNER(v,self);}
-(void)setPr_iv_Clas_ivar:(Clas*)v {MSGSTART("VarsAssignAtomic:-(void)setPr_iv_Clas_ivar:(Clas*)v")
  
  /*i-905*/if(v_pr_iv_Clas_ivar==v)return;
  /*i-900*/{v_pr_iv_Clas_ivar=(id)v;}
/*i-850*/REMOVEOWNER(v_pr_iv_Clas_ivar,self);ADDOWNER(v,self);}
-(void)setPr_iv_Clas_ivar_named:(Clas*)v {MSGSTART("VarsAssignAtomic:-(void)setPr_iv_Clas_ivar_named:(Clas*)v")
  
  /*i-905*/if(the_ivar_named==v)return;
  /*i-900*/{the_ivar_named=(id)v;}
/*i-850*/REMOVEOWNER(the_ivar_named,self);ADDOWNER(v,self);}
-(void)setPr_iv_Clas_setter:(Clas*)v {MSGSTART("VarsAssignAtomic:-(void)setPr_iv_Clas_setter:(Clas*)v")
  pr_iv_Clas_setter=[Clas getDefault];}
-(void)setRw_iv_Clas_settergetter2:(Clas*)v {MSGSTART("VarsAssignAtomic:-(void)setRw_iv_Clas_settergetter2:(Clas*)v")
}
-(void)setRw_iv_Clas_settergetter:(Clas*)v {MSGSTART("VarsAssignAtomic:-(void)setRw_iv_Clas_settergetter:(Clas*)v")
  rw_iv_Clas_settergetter=[Clas getDefault];}
-(void)setRw_iv_Clas_setteri:(Clas*)v {MSGSTART("VarsAssignAtomic:-(void)setRw_iv_Clas_setteri:(Clas*)v")
  rw_iv_Clas_setteri=[Clas getDefault];}
-(void)setRw_iv_def_Clas_atomici:(Clas*)v {MSGSTART("VarsAssignAtomic:-(void)setRw_iv_def_Clas_atomici:(Clas*)v")
  
  /*i-905*/@synchronized(self) {
    /*i-904*/if(v_rw_iv_def_Clas_atomici==v)return;
    /*i-900*/{v_rw_iv_def_Clas_atomici=(id)v;}
  /*i-895*/}
  /*i-850*/REMOVEOWNER(v_rw_iv_def_Clas_atomici,self);ADDOWNER(v,self);}
-(void)setRw_jiv_Clas_justivar_named:(Clas*)v {MSGSTART("VarsAssignAtomic:-(void)setRw_jiv_Clas_justivar_named:(Clas*)v")
  
  /*i-905*/if(the_justivar_named==v)return;
  /*i-900*/{the_justivar_named=(id)v;}
/*i-850*/REMOVEOWNER(the_justivar_named,self);ADDOWNER(v,self);}
-(void)setRw_noiv_Clas_settergetter:(Clas*)v {MSGSTART("VarsAssignAtomic:-(void)setRw_noiv_Clas_settergetter:(Clas*)v")
}
-(void)setRw_noiv_Clas_setteri:(Clas*)v {MSGSTART("VarsAssignAtomic:-(void)setRw_noiv_Clas_setteri:(Clas*)v")
}
-(void)setSG:(Clas*)v {MSGSTART("VarsAssignAtomic:-(void)setSG:(Clas*)v")
  
  /*i-905*/if(v_rw_iv_Clas_settergetteri==v)return;
  /*i-900*/{v_rw_iv_Clas_settergetteri=(id)v;}
/*i-850*/REMOVEOWNER(v_rw_iv_Clas_settergetteri,self);ADDOWNER(v,self);}
-(Clas*)sg {MSGSTART("VarsAssignAtomic:-(Clas*)sg")
  
  /*i-999*/Clas* ret=v_rw_iv_Clas_settergetteri;
  /*i999*/return(ret);}
-(void)testGetterSetter {MSGSTART("VarsAssignAtomic:-(void)testGetterSetter")

          pr_iv_def_Clas_publicreadonly=pr_iv_def_Clas_publicreadonly;
          rw_iv_def_Clas_atomici=rw_iv_def_Clas_atomici;
          rw_iv_Clas_settergetteri=rw_iv_Clas_settergetteri;
          pr_iv_Clas_getteri=r_noiv_Clas_getteri;
          pr_iv_Clas_getteri=pr_iv_Clas_getteri;
          pr_iv_Clas_setter=pr_iv_Clas_setter;
          rw_iv_Clas_setteri=rw_iv_Clas_setteri;
          rw_noiv_Clas_setteri=rw_noiv_Clas_setteri;
          rw_iv_Clas_settergetter=rw_iv_Clas_settergetter;
          rw_iv_Clas_settergetter2=rw_iv_Clas_settergetter2;
          pr_iv_Clas_ivar=pr_iv_Clas_ivar;
          pr_iv_Clas_ivar_named=pr_iv_Clas_ivar_named;
    }
-(id)w_autorelease {MSGSTART("VarsAssignAtomic:-(id)w_autorelease")
  
  /*i-900*/autoreleaseFn(self,___rc,___arc,debugAutorelease); 
  /*i990*/return(nil/*super*/);}
-(void)w_release {MSGSTART("VarsAssignAtomic:-(void)w_release")
  
  /*i-900*/releaseFn(self,___rc,___arc,debugAutorelease); }
-(id)w_retain {MSGSTART("VarsAssignAtomic:-(id)w_retain")
  
  /*i-900*/retainFn(self,___rc,___arc); 
  /*i999*/return(nil/*super*/);}

@end
#undef _ClassName_
#undef _WIClass_
#undef _className_
#undef _Class_


















